<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PartnerShop;
use Illuminate\Support\Facades\Hash;

class PartnerShopsSeeder extends Seeder
{
    public function run()
    {
        $partnerShops = [
            [
                'partner_shops_name' => 'Infinity Tech Store',
                'partner_shops_email' => 'infinitytech@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Kyauktada',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Code& Pixel',
                'partner_shops_email' => 'codepixel@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Lanmadaw',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Cloud Connectors',
                'partner_shops_email' => 'cloudconnectors@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Bahan',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'The Data Den',
                'partner_shops_email' => 'thedataden@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Kyauktada',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Innovate IT',
                'partner_shops_email' => 'innovateit@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Sanchaung',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Tech Fusion Store',
                'partner_shops_email' => 'techfusion@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Kyauktada',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Hardware Haven',
                'partner_shops_email' => 'hardwarehaven@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Lanmadaw',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Binary Boutique',
                'partner_shops_email' => 'binaryboutique@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Kyauktada',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Circuit City Pro',
                'partner_shops_email' => 'circuitcity@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Mingalar Taung Nyunt',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'GigaWorld Electronics',
                'partner_shops_email' => 'gigaworld@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Sanchaung',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Mega Tech Mart',
                'partner_shops_email' => 'megatechmart@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Mingalar Taung Nyunt',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'CyberCore',
                'partner_shops_email' => 'cybercore@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Pabedan',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'PC Planet',
                'partner_shops_email' => 'pcplanet@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Pabedan',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Byte Bazaar',
                'partner_shops_email' => 'bytebazaar@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Sanchaung',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'Future Bytes',
                'partner_shops_email' => 'futurebytes@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Tamwe',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'IT Essentials Co.',
                'partner_shops_email' => 'itessentials@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Yankin',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'SmartEdge Solutions',
                'partner_shops_email' => 'smartedge@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Kamaryut',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'DigitalHub',
                'partner_shops_email' => 'digitalhub@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Bahan',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'NextGen Gadgets',
                'partner_shops_email' => 'nextgengadgets@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Bahan',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
            [
                'partner_shops_name' => 'TechNest',
                'partner_shops_email' => 'technest@example.com',
                'partner_shops_password' => Hash::make('pwd1234'),
                'partner_shops_address' => null,
                'partner_shops_township' => 'Ahlone',
                'partner_shops_region' => 'Yangon',
                'contact_primary' => null,
                'contact_secondary' => null,
            ],
        ];

        foreach ($partnerShops as $shop) {
            PartnerShop::create($shop);
        }
    }
}
