<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SalesInvoice;

class SalesInvoiceSeeder extends Seeder
{
    public function run()
    {
        $salesInvoices = [
            [
                'sale_date' => '2025-01-05',
                'invoice_no' => 'INV-1001',
                'partner_shops_id' => 1,
                'item_name' => 'Apple MacBook Pro 14-inch',
                'brand' => 'Apple',
                'category' => 'Laptop',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'MBP14-2025-A1B2C3D4E5',
                'unit_price_mmk' => 1800000.00,
                'cash_back_mmk' => 50000.00,
                'quantity' => 3,
                'total_mmk' => 5400000.00,
                'remarks' => 'Space Black 1, Silver 2',
            ],
            [
                'sale_date' => '2025-01-06',
                'invoice_no' => 'INV-1002',
                'partner_shops_id' => 2,
                'item_name' => 'Intel Core i7-13700K CPU',
                'brand' => 'Intel',
                'category' => 'Processor',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'INTEL-I713700K-XYZ12345',
                'unit_price_mmk' => 300000.00,
                'cash_back_mmk' => 0.00,
                'quantity' => 4,
                'total_mmk' => 1200000.00,
                'remarks' => '',
            ],
            [
                'sale_date' => '2025-01-07',
                'invoice_no' => 'INV-1003',
                'partner_shops_id' => 3,
                'item_name' => 'HP EliteBook 840',
                'brand' => 'HP',
                'category' => 'Laptop',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'HP840-G8-12AB34CD56',
                'unit_price_mmk' => 800000.00,
                'cash_back_mmk' => 25000.00,
                'quantity' => 5,
                'total_mmk' => 4000000.00,
                'remarks' => '',
            ],
            [
                'sale_date' => '2025-01-07',
                'invoice_no' => 'INV-1004',
                'partner_shops_id' => 4,
                'item_name' => 'LG UltraGear 27-inch',
                'brand' => 'LG',
                'category' => 'Monitor',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'LGUG-27GP950-ABC12345D',
                'unit_price_mmk' => 800000.00,
                'cash_back_mmk' => 15000.00,
                'quantity' => 1,
                'total_mmk' => 800000.00,
                'remarks' => '',
            ],
            [
                'sale_date' => '2025-01-08',
                'invoice_no' => 'INV-1005',
                'partner_shops_id' => 5,
                'item_name' => 'WD Black SN850X 1TB SSD',
                'brand' => 'WD',
                'category' => 'Storage Device',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'WDB-SN850X1TB-X123Y456Z',
                'unit_price_mmk' => 250000.00,
                'cash_back_mmk' => 10000.00,
                'quantity' => 15,
                'total_mmk' => 3750000.00,
                'remarks' => '',
            ],
            [
                'sale_date' => '2025-01-08',
                'invoice_no' => 'INV-1006',
                'partner_shops_id' => 19,
                'item_name' => 'Samsung 970 EVO Plus 2TB SSD',
                'brand' => 'Samsung',
                'category' => 'Storage Device',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'SAM970EVO2TB-XYZ123',
                'unit_price_mmk' => 320000.00,
                'cash_back_mmk' => 12000.00,
                'quantity' => 10,
                'total_mmk' => 3200000.00,
                'remarks' => '',
            ],
            [
                'sale_date' => '2025-01-09',
                'invoice_no' => 'INV-1007',
                'partner_shops_id' => 17,
                'item_name' => 'Razer DeathAdder V3 Pro',
                'brand' => 'Razer',
                'category' => 'Gaming Mouse',
                'product_segment' => 'Gaming',
                'product_serial_number' => 'RAZER-DAV3PRO-123ABC',
                'unit_price_mmk' => 250000.00,
                'cash_back_mmk' => 5000.00,
                'quantity' => 8,
                'total_mmk' => 2000000.00,
                'remarks' => 'Limited Edition White',
            ],
            [
                'sale_date' => '2025-01-10',
                'invoice_no' => 'INV-1008',
                'partner_shops_id' => 1,
                'item_name' => 'NVIDIA RTX 4070 Ti',
                'brand' => 'NVIDIA',
                'category' => 'Graphics Card',
                'product_segment' => 'Gaming',
                'product_serial_number' => 'RTX4070TI-X4Y5Z6',
                'unit_price_mmk' => 2000000.00,
                'cash_back_mmk' => 0.00,
                'quantity' => 2,
                'total_mmk' => 4000000.00,
                'remarks' => '',
            ],
            [
                'sale_date' => '2025-01-11',
                'invoice_no' => 'INV-1009',
                'partner_shops_id' => 2,
                'item_name' => 'Corsair Vengeance 32GB RAM',
                'brand' => 'Corsair',
                'category' => 'Memory',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'COR-32GB-DDR5-XYZ',
                'unit_price_mmk' => 450000.00,
                'cash_back_mmk' => 0.00,
                'quantity' => 6,
                'total_mmk' => 2700000.00,
                'remarks' => '',
            ],
            [
                'sale_date' => '2025-01-12',
                'invoice_no' => 'INV-1010',
                'partner_shops_id' => 3,
                'item_name' => 'Sony WH-1000XM5 Headphones',
                'brand' => 'Sony',
                'category' => 'Audio',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'SONY-WH1000XM5-123XYZ',
                'unit_price_mmk' => 700000.00,
                'cash_back_mmk' => 30000.00,
                'quantity' => 5,
                'total_mmk' => 3500000.00,
                'remarks' => 'Black and Silver Models',
            ],
            [
                'sale_date' => '2025-01-13',
                'invoice_no' => 'INV-1011',
                'partner_shops_id' => 4,
                'item_name' => 'Dell XPS 15',
                'brand' => 'Dell',
                'category' => 'Laptop',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'DELLXPS15-987ABC',
                'unit_price_mmk' => 2200000.00,
                'cash_back_mmk' => 0.00,
                'quantity' => 2,
                'total_mmk' => 4400000.00,
                'remarks' => 'Latest 2025 Model',
            ],
            [
                'sale_date' => '2025-01-14',
                'invoice_no' => 'INV-1012',
                'partner_shops_id' => 5,
                'item_name' => 'Logitech MX Master 3S',
                'brand' => 'Logitech',
                'category' => 'Mouse',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'LOGI-MX3S-XYZ123',
                'unit_price_mmk' => 150000.00,
                'cash_back_mmk' => 5000.00,
                'quantity' => 12,
                'total_mmk' => 1800000.00,
                'remarks' => '',
            ],
            [
                'sale_date' => '2025-01-15',
                'invoice_no' => 'INV-1013',
                'partner_shops_id' => 19,
                'item_name' => 'Asus ROG Strix Z790-E Motherboard',
                'brand' => 'Asus',
                'category' => 'Motherboard',
                'product_segment' => 'Gaming',
                'product_serial_number' => 'ASUS-Z790E-XYZ123',
                'unit_price_mmk' => 900000.00,
                'cash_back_mmk' => 20000.00,
                'quantity' => 3,
                'total_mmk' => 2700000.00,
                'remarks' => '',
            ],
            [
                'sale_date' => '2025-01-16',
                'invoice_no' => 'INV-1014',
                'partner_shops_id' => 17,
                'item_name' => 'Seagate FireCuda 530 4TB SSD',
                'brand' => 'Seagate',
                'category' => 'Storage Device',
                'product_segment' => 'Consumer',
                'product_serial_number' => 'SEAGATE-FC530-4TB-XYZ',
                'unit_price_mmk' => 550000.00,
                'cash_back_mmk' => 15000.00,
                'quantity' => 4,
                'total_mmk' => 2200000.00,
                'remarks' => 'For High-End Workstations',
            ],
        ];

        foreach ($salesInvoices as $invoice) {
            SalesInvoice::create($invoice);
        }
    }
}
