<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\StockRecord;

class StockRecordsSeeder extends Seeder
{
    public function run()
    {
        $stockRecords = [
            [
                'record_date' => '2025-02-07',
                'category' => 'Laptop',
                'model' => 'Dell XPS 13',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 25,
                'received' => 1,
                'dispatched' => 3,
                'closing_balance' => 23,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Laptop',
                'model' => 'Lenovo IdeaPad 5',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 13,
                'received' => 4,
                'dispatched' => 1,
                'closing_balance' => 16,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Laptop',
                'model' => 'HP EliteBook 840',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 15,
                'received' => 1,
                'dispatched' => 5,
                'closing_balance' => 11,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Laptop',
                'model' => 'Asus TUF Gaming F15',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 8,
                'received' => 2,
                'dispatched' => 3,
                'closing_balance' => 7,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Laptop',
                'model' => 'Acer Aspire 5',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 20,
                'received' => 5,
                'dispatched' => 8,
                'closing_balance' => 17,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Laptop',
                'model' => 'Apple MacBook Pro 14-inch',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 5,
                'received' => 0,
                'dispatched' => 3,
                'closing_balance' => 2,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Laptop',
                'model' => 'MSI Prestige 14',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 10,
                'received' => 4,
                'dispatched' => 3,
                'closing_balance' => 11,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Desktop PC',
                'model' => 'HP Omen 25L',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 4,
                'received' => 0,
                'dispatched' => 2,
                'closing_balance' => 2,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Desktop PC',
                'model' => 'Dell OptiPlex 7090',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 8,
                'received' => 3,
                'dispatched' => 5,
                'closing_balance' => 6,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Desktop PC',
                'model' => 'Asus ROG Strix G10',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 5,
                'received' => 0,
                'dispatched' => 3,
                'closing_balance' => 2,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Desktop PC',
                'model' => 'Microsoft Surface Studio',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 6,
                'received' => 0,
                'dispatched' => 5,
                'closing_balance' => 1,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Monitor',
                'model' => 'ViewSonic VX3276 Monitor',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 9,
                'received' => 2,
                'dispatched' => 7,
                'closing_balance' => 4,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Monitor',
                'model' => 'LG UltraGear 27-inch',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 4,
                'received' => 3,
                'dispatched' => 1,
                'closing_balance' => 6,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Monitor',
                'model' => 'Samsung Smart Monitor M8',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 5,
                'received' => 0,
                'dispatched' => 3,
                'closing_balance' => 2,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Accessories',
                'model' => 'Logitech MX Keys Keyboard',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 25,
                'received' => 5,
                'dispatched' => 20,
                'closing_balance' => 10,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Accessories',
                'model' => 'Razer Basilisk V3 Mouse',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 30,
                'received' => 0,
                'dispatched' => 12,
                'closing_balance' => 18,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Storage Device',
                'model' => 'Kingston NV2 2TB SSD',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 20,
                'received' => 5,
                'dispatched' => 8,
                'closing_balance' => 17,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Storage Device',
                'model' => 'WD Black SN850X 1TB SSD',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 21,
                'received' => 6,
                'dispatched' => 15,
                'closing_balance' => 12,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Storage Device',
                'model' => 'Seagate IronWolf 4TB HDD',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 15,
                'received' => 0,
                'dispatched' => 2,
                'closing_balance' => 13,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Storage Device',
                'model' => 'Samsung T7 Portable SSD',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 11,
                'received' => 6,
                'dispatched' => 5,
                'closing_balance' => 12,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Networking Device',
                'model' => 'TP-Link Deco XE75 Router',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 8,
                'received' => 0,
                'dispatched' => 2,
                'closing_balance' => 6,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Networking Device',
                'model' => 'Cisco Catalyst 9200 Switch',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 10,
                'received' => 2,
                'dispatched' => 3,
                'closing_balance' => 9,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Printer',
                'model' => 'Epson EcoTank ET-3850',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 5,
                'received' => 0,
                'dispatched' => 3,
                'closing_balance' => 2,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Printer',
                'model' => 'Canon Image CLASS MF644 CDW',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 10,
                'received' => 0,
                'dispatched' => 5,
                'closing_balance' => 5,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Software',
                'model' => 'Adobe Photoshop CC',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 9,
                'received' => 3,
                'dispatched' => 5,
                'closing_balance' => 7,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Software',
                'model' => 'Microsoft Office 2021',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 15,
                'received' => 2,
                'dispatched' => 7,
                'closing_balance' => 10,
                'system_users_id' => 1,
            ],
            [
                'record_date' => '2025-02-07',
                'category' => 'Software',
                'model' => 'Kaspersky Total Security',
                'warehouse_branch' => 'Dawbon',
                'opening_balance' => 21,
                'received' => 0,
                'dispatched' => 12,
                'closing_balance' => 9,
                'system_users_id' => 1,
            ],
        ];

        foreach ($stockRecords as $record) {
            StockRecord::create($record);
        }
    }
}
